### ISSUE TITLE
Precompute twiddle factors

### ISSUE THREAD

**Issue by jfsantos** [stainless-steel/dft#1] opened 2015-11-15 00:00 UTC
I am not sure on how far you want to go with this library, but one simple optimization would be to precompute the twiddle factors for a given N and reuse them when calling `transform` multiple times. Is this something you would be interested in having or do you want to keep the library as simple as possible?

**Comment by IvanUkhov** [comment] 2015-11-15 07:50
Thanks for the issue, João! I’m not dogmatic at all about the future of this library. If something can be shown to be clearly beneficial for the end user, I’ll totally support it.

I’m a bit unsure about how you propose to precompute the twiddle factors. Are you thinking about some kind of a constant array up to some N or about some kind of a per-thread static hash map that will be populated on the fly? If the former, the question is in choosing N and in what happens for M > N. If the latter, the question is in whether it will actually be computationally cheaper.

Regards,
Ivan

**Comment by jfsantos** [comment] 2015-11-15 15:32
Hi Ivan, thanks for your reply!

I think I did not express myself clearly: the idea is not pre-computing during compile time, but avoid having to compute the factors on each call with same length N.

In many domains, including audio signal processing, you end up performing a lot of FFTs with the same size of N (when computing a [Short-time Fourier Transform](https://en.wikipedia.org/wiki/Short-time_Fourier_transform), for example). To avoid computing the factors on each call, most FFT libraries have a function that pre-computes the factors and store it as a struct, which is later explicitly passed to the function that performs the transform. You'll see something like that in libraries like FFTW, KissFFT, and Apple's vDSP.

If we do something like this, storing the factors in a hash map could be an option to avoid computing the factors again in the case you have lots of different N in your application.

**Comment by IvanUkhov** [comment] 2015-11-16 08:29
Sounds good. [Here](https://github.com/stainless-steel/dft/tree/context) is one way of doing this. What is interesting is that the performance has improved for small datasets but not for large; for large, it might have even become worse. For instance, have a look at [this](https://travis-ci.org/stainless-steel/dft/jobs/86335396) (old) and [that](https://travis-ci.org/stainless-steel/dft/builds/91335544) (new).

**Comment by IvanUkhov** [comment] 2015-11-16 08:43
If you have a better (design- or performance-wise) implementation in mind, please feel free to open a pull request. Thanks.

**Comment by jfsantos** [comment] 2015-11-16 14:54
It looks good to me, design-wise. 

I thought what could be making accessing the `factors` array slower than computing the twiddle factors inline was that it is being accessed out of order (so bounds checking has to be performed), but accessing it via the unsafe `get_unchecked` method did not improve the performance beyond the error margins, so there's little reason to try to restructure the code to allow `factors` to be accessed in order.

I then thought accessing `data` with bounds checking could have a bigger impact in performance here, so I went and updated `complex.rs` to use an unsafe block whenever accessing `factors` and `data` (except in `rearrange`, where I did not change the `swap` call). Once again, the difference in performance was below the error margins:

With bounds checking:

```
running 12 tests
test complex_transform_0004 ... bench:          26 ns/iter (+/- 4)
test complex_transform_0016 ... bench:         133 ns/iter (+/- 23)
test complex_transform_0064 ... bench:         647 ns/iter (+/- 98)
test complex_transform_0256 ... bench:       3,032 ns/iter (+/- 1,121)
test complex_transform_1024 ... bench:      17,362 ns/iter (+/- 2,384)
test complex_transform_4096 ... bench:     131,597 ns/iter (+/- 50,947)
test real_transform_0004    ... bench:          41 ns/iter (+/- 8)
test real_transform_0016    ... bench:         189 ns/iter (+/- 61)
test real_transform_0064    ... bench:         817 ns/iter (+/- 250)
test real_transform_0256    ... bench:       4,282 ns/iter (+/- 722)
test real_transform_1024    ... bench:      21,536 ns/iter (+/- 3,603)
test real_transform_4096    ... bench:     155,263 ns/iter (+/- 27,249)
```

Without bounds checking in most places in `complex.rs`:

```
running 12 tests
test complex_transform_0004 ... bench:          22 ns/iter (+/- 9)
test complex_transform_0016 ... bench:         111 ns/iter (+/- 14)
test complex_transform_0064 ... bench:         564 ns/iter (+/- 163)
test complex_transform_0256 ... bench:       2,797 ns/iter (+/- 576)
test complex_transform_1024 ... bench:      14,304 ns/iter (+/- 4,431)
test complex_transform_4096 ... bench:     130,700 ns/iter (+/- 23,842)
test real_transform_0004    ... bench:          39 ns/iter (+/- 7)
test real_transform_0016    ... bench:         159 ns/iter (+/- 62)
test real_transform_0064    ... bench:         799 ns/iter (+/- 151)
test real_transform_0256    ... bench:       3,428 ns/iter (+/- 1,042)
test real_transform_1024    ... bench:      18,435 ns/iter (+/- 3,449)
test real_transform_4096    ... bench:     137,276 ns/iter (+/- 44,665)
```

Note that `rearrange` and anything in `real.rs` are probably still doing bounds checking. If you want, I can submit a PR with the updates that do not require `unsafe` blocks (or with all of the changes I've done, so you can benchmark the code as well).

**Comment by jfsantos** [comment] 2015-11-16 15:12
I created a fork and pushed my changes to the context branch: https://github.com/jfsantos/dft/blob/context/src/complex.rs

**Comment by IvanUkhov** [comment] 2015-11-16 17:24
I’ve merged `context` into `master` as I agree with you that precomputing factors is very valuable; other libraries are obviously doing this for a reason. However, the issue with a slowdown for large datasets still remains, and I’m curious to figure out what the cause is. Here is the state of affairs on my machine (I temporary added a pair of benchmarks for 8192 data points):

Before:

```
test complex_forward_0004 ... bench:          82 ns/iter (+/- 15)
test complex_forward_0016 ... bench:         217 ns/iter (+/- 99)
test complex_forward_0064 ... bench:         723 ns/iter (+/- 104)
test complex_forward_0256 ... bench:       2,717 ns/iter (+/- 479)
test complex_forward_1024 ... bench:      12,614 ns/iter (+/- 2,362)
test complex_forward_4096 ... bench:     109,016 ns/iter (+/- 16,100)
test complex_forward_8192 ... bench:     281,937 ns/iter (+/- 37,486)
test real_forward_0004    ... bench:         114 ns/iter (+/- 19)
test real_forward_0016    ... bench:         287 ns/iter (+/- 36)
test real_forward_0064    ... bench:         927 ns/iter (+/- 147)
test real_forward_0256    ... bench:       3,477 ns/iter (+/- 461)
test real_forward_1024    ... bench:      15,362 ns/iter (+/- 2,142)
test real_forward_4096    ... bench:     123,095 ns/iter (+/- 16,610)
test real_forward_8192    ... bench:     304,608 ns/iter (+/- 38,745)
```

After:

```
test complex_transform_0004 ... bench:          19 ns/iter (+/- 5)
test complex_transform_0016 ... bench:         100 ns/iter (+/- 17)
test complex_transform_0064 ... bench:         532 ns/iter (+/- 66)
test complex_transform_0256 ... bench:       2,381 ns/iter (+/- 358)
test complex_transform_1024 ... bench:      11,563 ns/iter (+/- 1,680)
test complex_transform_4096 ... bench:     136,356 ns/iter (+/- 24,746)
test complex_transform_8192 ... bench:     312,535 ns/iter (+/- 63,948)
test real_transform_0004    ... bench:          29 ns/iter (+/- 4)
test real_transform_0016    ... bench:         135 ns/iter (+/- 19)
test real_transform_0064    ... bench:         703 ns/iter (+/- 128)
test real_transform_0256    ... bench:       3,279 ns/iter (+/- 531)
test real_transform_1024    ... bench:      14,988 ns/iter (+/- 2,725)
test real_transform_4096    ... bench:     130,712 ns/iter (+/- 22,395)
test real_transform_8192    ... bench:     320,028 ns/iter (+/- 50,248)
```

I’m wondering if one additional function argument can have such an effect.

**Comment by jfsantos** [comment] 2015-11-17 03:53
I'm trying to profile the code on OS X but the native profiling tool (Time Profiler in Instruments) only gives me the runtime for the whole transform call. Maybe I'll have to write a test program with all the module functions as public so the profiler can "see" a little more. It's the first time I try to profile Rust code, so I don't know if we would have more luck trying to do this with the Linux profiling tools or if I'm doing it properly.

**Comment by IvanUkhov** [comment] 2015-11-17 05:44
I don’t know how Time Profiler works, but I hope that what you’re experiencing is not related to the [SIGPROF bug](http://research.swtch.com/macpprof) in Darwin, which prevents proper profiling on OS X.

**Comment by IvanUkhov** [comment] 2015-11-17 09:47
Below are some profiling results obtained via valgrind on a Linux machine. In order to make the profiler work correctly, `debug` is set to `true` in `Cargo.toml` for the `bench` profile. It seems that the debugging enabled skewed the results quite a bit.

# Before

```
$ valgrind --tool=callgrind ./target/release/lib-6a8f4f030eaf679d --bench complex_forward_8192
==14426== Callgrind, a call-graph generating cache profiler
==14426== Copyright (C) 2002-2012, and GNU GPL'd, by Josef Weidendorfer et al.
==14426== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==14426== Command: ./target/release/lib-6a8f4f030eaf679d --bench complex_forward_8192
==14426==
==14426== For interactive control, run 'callgrind_control -h'.
==14426== Warning: noted but unhandled ioctl 0x5451 with no size/direction hints
==14426==    This could cause spurious value errors to appear.
==14426==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
--14426-- WARNING: unhandled syscall: 318
--14426-- You may be able to write your own handler.
--14426-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--14426-- Nevertheless we consider this a bug.  Please report
--14426-- it at http://valgrind.org/support/bug_reports.html.
==14426== Warning: noted but unhandled ioctl 0x5451 with no size/direction hints
==14426==    This could cause spurious value errors to appear.
==14426==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.

running 1 test
test complex_forward_8192 ... bench:  12,154,341 ns/iter (+/- 47,765)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

==14426==
==14426== Events    : Ir
==14426== Collected : 509048449
==14426==
==14426== I   refs:      509,048,449
$ callgrind_annotate --auto=yes ./callgrind.out.14426
--------------------------------------------------------------------------------
Profile data file './callgrind.out.14426' (creator: callgrind-3.8.1)
--------------------------------------------------------------------------------
I1 cache:
D1 cache:
LL cache:
Timerange: Basic block 0 - 64623612
Trigger: Program termination
Profiled target:  ./target/release/lib-6a8f4f030eaf679d --bench complex_forward_8192 (PID 14426, part 1)
Events recorded:  Ir
Events shown:     Ir
Event sort order: Ir
Thresholds:       99
Include dirs:
User annotated:
Auto-annotation:  on

--------------------------------------------------------------------------------
         Ir
--------------------------------------------------------------------------------
509,048,449  PROGRAM TOTALS

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
295,925,441  ../src/libcore/ops.rs:complex::transform::hf13a3abd514dd18d6da
149,250,850  src/complex.rs:complex::transform::hf13a3abd514dd18d6da [/home/ivauk/code/github.com/stainless-steel/dft/target/release/lib-6a8f4f030eaf679d]
 30,825,109  src/complex.rs:complex::forward::hacf1f92266e81e40maa [/home/ivauk/code/github.com/stainless-steel/dft/target/release/lib-6a8f4f030eaf679d]
  7,281,792  ../src/libcore/ptr.rs:complex::forward::hacf1f92266e81e40maa
  6,068,160  ../src/libcore/slice.rs:complex::forward::hacf1f92266e81e40maa
  4,942,721  ../src/libcore/cmp.rs:complex::transform::hf13a3abd514dd18d6da
  4,931,584  ../src/libcore/cmp.rs:complex::forward::hacf1f92266e81e40maa
  2,465,792  ../src/libcore/ops.rs:complex::forward::hacf1f92266e81e40maa
  2,465,491  ../src/libcore/iter.rs:complex::transform::hf13a3abd514dd18d6da

--------------------------------------------------------------------------------
-- Auto-annotated source: src/complex.rs
--------------------------------------------------------------------------------
        Ir

-- line 3 ----------------------------------------
         .  // The implementation is based on:
         .  // http://www.librow.com/articles/article-10
         .
         .  use c64;
         .
         .  /// Perform the forward transform.
         .  ///
         .  /// The number of points should be a power of two.
     1,204  pub fn forward(data: &mut [c64]) {
         .      let n = power_of_two!(data);
 6,164,480      rearrange(data, n);
     1,806      transform(data, n, false);
453,525,435  => src/complex.rs:complex::transform::hf13a3abd514dd18d6da (301x)
         .  }
         .
         .  /// Perform the backward transform.
         .  ///
         .  /// The number of points should be a power of two.
         .  pub fn backward(data: &mut [c64]) {
         .      let n = power_of_two!(data);
         .      rearrange(data, n);
-- line 22 ----------------------------------------
-- line 31 ----------------------------------------
         .      rearrange(data, n);
         .      transform(data, n, true);
         .      scale(data, n);
         .  }
         .
         .  fn rearrange(data: &mut [c64], n: usize) {
         .      let mut j = 0;
         .      for i in 0..n {
 4,931,584          if j > i {
         .              data.swap(i, j);
         .          }
 2,466,996          let mut mask = n >> 1;
 7,396,774          while j & mask != 0 {
 7,396,473              j &= !mask;
         .              mask >>= 1;
         .          }
 2,465,792          j |= mask;
         .      }
         .  }
         .
     5,117  fn transform(data: &mut [c64], n: usize, inverse: bool) {
         .      let sign = if inverse { 1.0 } else { -1.0 };
         .      let mut step = 1;
    12,642      while step < n {
     3,913          let jump = step << 1;
         .          let (multiplier, mut factor) = {
         .              use std::f64::consts::PI;
    27,391              let theta = sign * PI / step as f64;
     7,826              let sine = (0.5 * theta).sin();
    11,739              (c64!(-2.0 * sine * sine, theta.sin()), c64!(1.0, 0.0))
         .          };
         .          for mut i in 0..step {
53,013,926              while i < n {
         .                  let j = i + step;
48,082,944                  let product = factor * data[j];
32,055,296                  data[j] = data[i] - product;
         .                  data[i] = data[i] + product;
16,027,648                  i += jump;
         .              }
         .              factor = multiplier * factor + factor;
         .          }
         .          step <<= 1;
         .      }
     2,408  }
         .
         .  fn scale(data: &mut [c64], n: usize) {
         .      let factor = 1.0 / n as f64;
         .      for i in 0..n {
         .          data[i] = data[i].scale(factor);
         .      }
         .  }

--------------------------------------------------------------------------------
The following files chosen for auto-annotation could not be found:
--------------------------------------------------------------------------------
  ../src/libcore/ptr.rs
  ../src/libcore/iter.rs
  ../src/libcore/ops.rs
  ../src/libcore/cmp.rs
  ../src/libcore/slice.rs

--------------------------------------------------------------------------------
Ir
--------------------------------------------------------------------------------
35  percentage of events annotated
```

# After

```
$ valgrind --tool=callgrind ./target/release/lib-6a8f4f030eaf679d --bench complex_8192
==14499== Callgrind, a call-graph generating cache profiler
==14499== Copyright (C) 2002-2012, and GNU GPL'd, by Josef Weidendorfer et al.
==14499== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==14499== Command: ./target/release/lib-6a8f4f030eaf679d --bench complex_8192
==14499==
==14499== For interactive control, run 'callgrind_control -h'.
==14499== Warning: noted but unhandled ioctl 0x5451 with no size/direction hints
==14499==    This could cause spurious value errors to appear.
==14499==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
--14499-- WARNING: unhandled syscall: 318
--14499-- You may be able to write your own handler.
--14499-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--14499-- Nevertheless we consider this a bug.  Please report
--14499-- it at http://valgrind.org/support/bug_reports.html.
==14499== Warning: noted but unhandled ioctl 0x5451 with no size/direction hints
==14499==    This could cause spurious value errors to appear.
==14499==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.

running 1 test
test complex_8192 ... bench:  10,607,513 ns/iter (+/- 85,337)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

==14499==
==14499== Events    : Ir
==14499== Collected : 511688533
==14499==
==14499== I   refs:      511,688,533
$ callgrind_annotate --auto=yes ./callgrind.out.14499
--------------------------------------------------------------------------------
Profile data file './callgrind.out.14499' (creator: callgrind-3.8.1)
--------------------------------------------------------------------------------
I1 cache:
D1 cache:
LL cache:
Timerange: Basic block 0 - 52824013
Trigger: Program termination
Profiled target:  ./target/release/lib-6a8f4f030eaf679d --bench complex_8192 (PID 14499, part 1)
Events recorded:  Ir
Events shown:     Ir
Event sort order: Ir
Thresholds:       99
Include dirs:
User annotated:
Auto-annotation:  on

--------------------------------------------------------------------------------
         Ir
--------------------------------------------------------------------------------
511,688,533  PROGRAM TOTALS

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
250,310,396  src/complex.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa [/home/ivauk/code/github.com/stainless-steel/dft/target/release/lib-6a8f4f030eaf679d]
213,306,359  ../src/libcore/ops.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa
  9,871,596  ../src/libcore/cmp.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa
  9,110,705  ../src/libcore/ops.rs:_$LT$impl$GT$::new::h2a068a6cfa249930Lra
  7,281,792  ../src/libcore/ptr.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa
  6,068,160  ../src/libcore/slice.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa
  5,799,521  ../src/libcollections/vec.rs:_$LT$impl$GT$::new::h2a068a6cfa249930Lra
  2,465,491  ../src/libcore/iter.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa
  1,658,521  ../src/libcore/cmp.rs:_$LT$impl$GT$::new::h2a068a6cfa249930Lra
  1,213,632  ../src/libcollections/slice.rs:complex::_$LT$impl$GT$::transform::h8e5a44a6f679431braa

--------------------------------------------------------------------------------
-- Auto-annotated source: src/complex.rs
--------------------------------------------------------------------------------
         Ir

          .  // The implementation is based on:
          .  // http://www.librow.com/articles/article-10
          .
          .  use {Operation, Plan, Transform, c64};
        602
          .  impl Transform for [c64] {
      3,311      fn transform(&mut self, plan: &Plan) {
          .          let n = self.len();
          .          assert!(n <= plan.size, "the plan is not appropriate for the dataset");
  6,164,480          rearrange(self, n);
131,933,116          calculate(self, n, &plan.factors);
      1,204          if let Operation::Inverse = plan.operation {
          .              scale(self, n);
          .          }
      2,408      }
          .  }
          .
          .  #[inline(always)]
          .  fn calculate(data: &mut [c64], n: usize, factors: &[c64]) {
          .      let mut k = 0;
          .      let mut step = 1;
      8,729      while step < n {
      3,913          let jump = step << 1;
          .          for mut i in 0..step {
 53,013,926              while i < n {
          .                  let j = i + step;
 16,027,648                  let product = factors[k] * data[j];
          .                  data[j] = data[i] - product;
          .                  data[i] = data[i] + product;
 16,027,648                  i += jump;
          .              }
  2,465,491              k += 1;
          .          }
          .          step <<= 1;
          .      }
          .  }
          .
          .  #[inline(always)]
          .  fn rearrange(data: &mut [c64], n: usize) {
          .      let mut j = 0;
          .      for i in 0..n {
  4,931,584          if j > i {
          .              data.swap(i, j);
          .          }
  2,467,297          let mut mask = n >> 1;
  7,396,774          while j & mask != 0 {
  7,396,473              j &= !mask;
          .              mask >>= 1;
          .          }
  2,465,792          j |= mask;
          .      }
          .  }
          .
          .  #[inline(always)]
          .  fn scale(data: &mut [c64], n: usize) {
          .      let factor = 1.0 / n as f64;
          .      for i in 0..n {
          .          data[i] = data[i].scale(factor);
-- line 58 ----------------------------------------

--------------------------------------------------------------------------------
The following files chosen for auto-annotation could not be found:
--------------------------------------------------------------------------------
  ../src/libcore/ptr.rs
  ../src/libcore/slice.rs
  ../src/libcollections/slice.rs
  ../src/libcore/ops.rs
  ../src/libcore/cmp.rs
  ../src/libcollections/vec.rs
  ../src/libcore/iter.rs

--------------------------------------------------------------------------------
Ir
--------------------------------------------------------------------------------
49  percentage of events annotated
```

**Closed as completed** 2016-04-04 08:13 UTC
